export const queryKeys = {
  me: ['me'] as const,
  lawyerProfile: ['lawyer-profile'] as const,
  currentPlan: ['plans', 'current'] as const,
  plans: ['plans'] as const,
  chats: ['chats'] as const,
  chat: (id: string) => ['chats', id] as const,
  chatDocuments: (chatId: string) => ['documents', 'chat', chatId] as const,
  folderDocuments: (folderId: string) => ['documents', 'folder', folderId] as const,
  document: (id: string) => ['documents', id] as const,
  documentAnalysis: (id: string) => ['documents', id, 'analysis'] as const,
  folders: ['folders'] as const,
  skills: ['skills'] as const,
  chatTasks: (chatId: string) => ['ai-tasks', 'chat', chatId] as const,
  task: (id: string) => ['ai-tasks', id] as const,
  users: ['admin', 'users'] as const,
  user: (id: string) => ['admin', 'users', id] as const,
  verifications: (status?: string) => ['admin', 'verifications', status ?? 'all'] as const,
  verification: (id: string) => ['admin', 'verifications', 'detail', id] as const,
}
